name: todopatamus
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  flutter: 
    sdk: flutter

  get_storage: ^2.1.1
  get: 4.6.6
  equatable: ^2.0.5

  handy_window: ^0.3.1
  google_fonts: ^6.1.0
  flutter_tabler_icons: ^1.9.0

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

